name = "mufarrrobeats"
main = "dist/index.js"
account_id = "ec4ad45dd996c96efeb70a4aec199cc4"
preview_urls = false
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2026-03-21"

